// ============================================================
// bookingSeedData.js
// Seed data dummy untuk halaman Bookings & CheckIn
//
// CARA PAKAI:
//   Copy-paste seluruh file ini ke browser console
//   saat aplikasi sudah terbuka, lalu refresh halaman.
//
//   Atau import di main.jsx / App.jsx (dev only):
//   import './bookingSeedData.js'
// ============================================================

;(function seedBookings() {
  const KEY = 'garage_bookings'

  // Jangan overwrite kalau sudah ada data
  const existing = sessionStorage.getItem(KEY)
  if (existing && JSON.parse(existing).length > 0) {
    console.log('[Seed] garage_bookings sudah ada data, skip.')
    return
  }

  // ── Helper tanggal relatif ────────────────────────────────
  function dateOffset(n) {
    const d = new Date()
    d.setDate(d.getDate() + n)
    return d.toISOString().slice(0, 10)
  }

  function isoOffset(n, h = 10, m = 0) {
    const d = new Date()
    d.setDate(d.getDate() + n)
    d.setHours(h, m, 0, 0)
    return d.toISOString()
  }

  const today     = dateOffset(0)
  const yesterday = dateOffset(-1)
  const tomorrow  = dateOffset(1)
  const in2days   = dateOffset(2)
  const in3days   = dateOffset(3)
  const in5days   = dateOffset(5)
  const in7days   = dateOffset(7)

  // ── Status enum (sama persis dengan statusConstants.js) ──
  const S = {
    WAITING_CONFIRMATION:  'Menunggu Konfirmasi',
    CONFIRMED:             'Dikonfirmasi',
    WAITING_CHECK_IN:      'Menunggu Check In',
    RESCHEDULED:           'Dijadwalkan Ulang',
    CHECKED_IN:            'Check In',
    NO_SHOW:               'No Show',
    CANCELLED_BY_CUSTOMER: 'Dibatalkan Customer',
    REJECTED:              'Ditolak',
    EXPIRED:               'Expired',
  }

  const bookings = [

    // ── 1. MENUNGGU KONFIRMASI (baru masuk, perlu aksi admin) ─
    {
      id: 'BK-DEMO0001',
      customerId: 'cust-001',
      customerName: 'Budi Santoso',
      customerPhone: '081234567890',
      vehicleDisplay: 'Toyota Avanza - B 1234 ABC',
      vehiclePlate: 'B 1234 ABC',
      vehicleId: null,
      serviceId: 'L01',
      serviceName: 'Service Berkala',
      estimatedPrice: 450000,
      estimatedDuration: '2–3 Jam',
      date: tomorrow,
      time: '09:00',
      notes: 'Oli mesin sudah 5000 km, tolong cek rem belakang juga.',
      status: S.WAITING_CONFIRMATION,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: null, confirmedBy: null,
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: null, mechanicName: null, serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-1, 14, 30),
      updatedAt: isoOffset(-1, 14, 30),
    },

    // ── 2. MENUNGGU KONFIRMASI ────────────────────────────────
    {
      id: 'BK-DEMO0002',
      customerId: 'cust-002',
      customerName: 'Siti Rahayu',
      customerPhone: '082345678901',
      vehicleDisplay: 'Honda Jazz - D 5678 XYZ',
      vehiclePlate: 'D 5678 XYZ',
      vehicleId: null,
      serviceId: 'L06',
      serviceName: 'Service AC',
      estimatedPrice: 350000,
      estimatedDuration: '2–5 Jam',
      date: in2days,
      time: '10:00',
      notes: 'AC sudah tidak dingin sejak 2 minggu lalu.',
      status: S.WAITING_CONFIRMATION,
      voucherCode: 'AC25',
      discountApplied: 87500,
      confirmedAt: null, confirmedBy: null,
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: null, mechanicName: null, serviceBay: null,
      source: 'online',
      createdAt: isoOffset(0, 8, 15),
      updatedAt: isoOffset(0, 8, 15),
    },

    // ── 3. MENUNGGU KONFIRMASI ────────────────────────────────
    {
      id: 'BK-DEMO0003',
      customerId: 'cust-003',
      customerName: 'Andi Wijaya',
      customerPhone: '083456789012',
      vehicleDisplay: 'Mitsubishi Xpander - BA 9012 DEF',
      vehiclePlate: 'BA 9012 DEF',
      vehicleId: null,
      serviceId: 'L07',
      serviceName: 'Service Mesin',
      estimatedPrice: 1500000,
      estimatedDuration: '1–3 Hari',
      date: in3days,
      time: '08:00',
      notes: 'Mesin kasar dan ada suara ngelitik saat digas.',
      status: S.WAITING_CONFIRMATION,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: null, confirmedBy: null,
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: null, mechanicName: null, serviceBay: null,
      source: 'online',
      createdAt: isoOffset(0, 9, 45),
      updatedAt: isoOffset(0, 9, 45),
    },

    // ── 4. DIKONFIRMASI — jadwal besok ────────────────────────
    {
      id: 'BK-DEMO0004',
      customerId: 'cust-004',
      customerName: 'Dewi Kusuma',
      customerPhone: '084567890123',
      vehicleDisplay: 'Suzuki Ertiga - BA 3456 GHI',
      vehiclePlate: 'BA 3456 GHI',
      vehicleId: null,
      serviceId: 'L02',
      serviceName: 'Tune Up',
      estimatedPrice: 600000,
      estimatedDuration: '3–4 Jam',
      date: tomorrow,
      time: '10:30',
      notes: 'Performa mesin terasa menurun, bensin boros.',
      status: S.CONFIRMED,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-1, 16, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: 'MK-001', mechanicName: 'Ahmad Supriyadi', serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-2, 11, 0),
      updatedAt: isoOffset(-1, 16, 0),
    },

    // ── 5. MENUNGGU CHECK IN — jadwal hari ini ────────────────
    {
      id: 'BK-DEMO0005',
      customerId: 'cust-005',
      customerName: 'Reza Pratama',
      customerPhone: '085678901234',
      vehicleDisplay: 'Daihatsu Xenia - BA 7890 JKL',
      vehiclePlate: 'BA 7890 JKL',
      vehicleId: null,
      serviceId: 'L03',
      serviceName: 'Ganti Oli',
      estimatedPrice: 250000,
      estimatedDuration: '30–60 Menit',
      date: today,
      time: '09:30',
      notes: '',
      status: S.WAITING_CHECK_IN,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-2, 14, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: 'MK-002', mechanicName: 'Beni Hartono', serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-3, 10, 0),
      updatedAt: isoOffset(-2, 14, 0),
    },

    // ── 6. MENUNGGU CHECK IN — jadwal hari ini ────────────────
    {
      id: 'BK-DEMO0006',
      customerId: 'cust-006',
      customerName: 'Linda Permata',
      customerPhone: '086789012345',
      vehicleDisplay: 'Toyota Rush - B 2345 MNO',
      vehiclePlate: 'B 2345 MNO',
      vehicleId: null,
      serviceId: 'L04',
      serviceName: 'Spooring',
      estimatedPrice: 200000,
      estimatedDuration: '1–2 Jam',
      date: today,
      time: '13:00',
      notes: 'Setir agak belok kiri sendiri saat jalan lurus.',
      status: S.WAITING_CHECK_IN,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-1, 9, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: 'MK-003', mechanicName: 'Candra Lim', serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-2, 15, 30),
      updatedAt: isoOffset(-1, 9, 0),
    },

    // ── 7. SUDAH CHECK IN — hari ini ─────────────────────────
    {
      id: 'BK-DEMO0007',
      customerId: 'cust-007',
      customerName: 'Fajar Nugroho',
      customerPhone: '087890123456',
      vehicleDisplay: 'Honda Brio - D 4567 PQR',
      vehiclePlate: 'D 4567 PQR',
      vehicleId: null,
      serviceId: 'L05',
      serviceName: 'Balancing',
      estimatedPrice: 150000,
      estimatedDuration: '1 Jam',
      date: today,
      time: '08:00',
      notes: 'Setir getar di kecepatan 80 km/jam ke atas.',
      status: S.CHECKED_IN,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-1, 10, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: isoOffset(0, 8, 5),
      checkInBy: 'Admin',
      orderId: '#ORD-DEMO0007',
      calendarEntryId: null, mechanicId: 'MK-001', mechanicName: 'Ahmad Supriyadi', serviceBay: 'Bay 2',
      source: 'online',
      createdAt: isoOffset(-3, 13, 0),
      updatedAt: isoOffset(0, 8, 5),
    },

    // ── 8. DIJADWALKAN ULANG (perlu aksi admin) ───────────────
    {
      id: 'BK-DEMO0008',
      customerId: 'cust-008',
      customerName: 'Maya Indira',
      customerPhone: '088901234567',
      vehicleDisplay: 'Nissan Grand Livina - BA 6789 STU',
      vehiclePlate: 'BA 6789 STU',
      vehicleId: null,
      serviceId: 'L08',
      serviceName: 'Service Kelistrikan',
      estimatedPrice: 400000,
      estimatedDuration: '2–8 Jam',
      date: in5days,
      time: '09:00',
      notes: 'Lampu check engine menyala, sensor mana yang bermasalah?',
      status: S.RESCHEDULED,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-3, 11, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: isoOffset(-1, 15, 0),
      rescheduledFrom: dateOffset(-3 + 2),
      rescheduledTime: '11:00',
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: null, mechanicName: null, serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-5, 16, 0),
      updatedAt: isoOffset(-1, 15, 0),
    },

    // ── 9. DIKONFIRMASI — 5 hari lagi ────────────────────────
    {
      id: 'BK-DEMO0009',
      customerId: 'cust-009',
      customerName: 'Hendra Saputra',
      customerPhone: '089012345678',
      vehicleDisplay: 'Toyota Fortuner - B 5678 VWX',
      vehiclePlate: 'B 5678 VWX',
      vehicleId: null,
      serviceId: 'L07',
      serviceName: 'Service Mesin',
      estimatedPrice: 3500000,
      estimatedDuration: '1–3 Hari',
      date: in5days,
      time: '08:00',
      notes: 'Overhaul ringan, ganti packing head.',
      status: S.CONFIRMED,
      voucherCode: 'HEMAT30',
      discountApplied: 1050000,
      confirmedAt: isoOffset(-1, 13, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: 'MK-002', mechanicName: 'Beni Hartono', serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-4, 9, 0),
      updatedAt: isoOffset(-1, 13, 0),
    },

    // ── 10. NO SHOW — kemarin ────────────────────────────────
    {
      id: 'BK-DEMO0010',
      customerId: 'cust-010',
      customerName: 'Rina Oktaviani',
      customerPhone: '081122334455',
      vehicleDisplay: 'Kia Sportage - BA 1122 YZA',
      vehiclePlate: 'BA 1122 YZA',
      vehicleId: null,
      serviceId: 'L01',
      serviceName: 'Service Berkala',
      estimatedPrice: 450000,
      estimatedDuration: '2–3 Jam',
      date: yesterday,
      time: '14:00',
      notes: '',
      status: S.NO_SHOW,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-3, 10, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: isoOffset(-1, 16, 0),
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: 'MK-003', mechanicName: 'Candra Lim', serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-5, 12, 0),
      updatedAt: isoOffset(-1, 16, 0),
    },

    // ── 11. DITOLAK ───────────────────────────────────────────
    {
      id: 'BK-DEMO0011',
      customerId: 'cust-011',
      customerName: 'Doni Kurniawan',
      customerPhone: '082233445566',
      vehicleDisplay: 'BMW 320i - B 8888 ZZZ',
      vehiclePlate: 'B 8888 ZZZ',
      vehicleId: null,
      serviceId: 'L07',
      serviceName: 'Service Mesin',
      estimatedPrice: 2000000,
      estimatedDuration: '1–3 Hari',
      date: yesterday,
      time: '09:00',
      notes: 'Mesin overheat.',
      status: S.REJECTED,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: null, confirmedBy: null,
      rejectedAt: isoOffset(-2, 11, 0),
      rejectedReason: 'Kapasitas bay penuh untuk tanggal tersebut. Silakan booking ulang.',
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: null, mechanicName: null, serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-4, 17, 0),
      updatedAt: isoOffset(-2, 11, 0),
    },

    // ── 12. DIBATALKAN CUSTOMER ───────────────────────────────
    {
      id: 'BK-DEMO0012',
      customerId: 'cust-012',
      customerName: 'Nita Sari',
      customerPhone: '083344556677',
      vehicleDisplay: 'Honda CR-V - D 3344 BCD',
      vehiclePlate: 'D 3344 BCD',
      vehicleId: null,
      serviceId: 'L06',
      serviceName: 'Service AC',
      estimatedPrice: 800000,
      estimatedDuration: '2–5 Jam',
      date: in7days,
      time: '11:00',
      notes: '',
      status: S.CANCELLED_BY_CUSTOMER,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-1, 9, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: null, mechanicName: null, serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-3, 14, 0),
      updatedAt: isoOffset(0, 7, 0),
    },

    // ── 13. MENUNGGU CHECK IN — hari ini ─────────────────────
    {
      id: 'BK-DEMO0013',
      customerId: 'cust-013',
      customerName: 'Yusuf Hakim',
      customerPhone: '084455667788',
      vehicleDisplay: 'Toyota Innova - BA 5566 EFG',
      vehiclePlate: 'BA 5566 EFG',
      vehicleId: null,
      serviceId: 'L02',
      serviceName: 'Tune Up',
      estimatedPrice: 700000,
      estimatedDuration: '3–4 Jam',
      date: today,
      time: '14:00',
      notes: 'Terakhir tune up 1 tahun lalu.',
      status: S.WAITING_CHECK_IN,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(-2, 16, 30),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: 'MK-001', mechanicName: 'Ahmad Supriyadi', serviceBay: null,
      source: 'walk-in',
      createdAt: isoOffset(-4, 11, 0),
      updatedAt: isoOffset(-2, 16, 30),
    },

    // ── 14. DIKONFIRMASI — besok ──────────────────────────────
    {
      id: 'BK-DEMO0014',
      customerId: 'cust-014',
      customerName: 'Putri Amalia',
      customerPhone: '085566778899',
      vehicleDisplay: 'Suzuki Swift - D 7788 HIJ',
      vehiclePlate: 'D 7788 HIJ',
      vehicleId: null,
      serviceId: 'L04',
      serviceName: 'Spooring',
      estimatedPrice: 175000,
      estimatedDuration: '1–2 Jam',
      date: tomorrow,
      time: '13:30',
      notes: '',
      status: S.CONFIRMED,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: isoOffset(0, 10, 0),
      confirmedBy: 'Admin',
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: 'MK-003', mechanicName: 'Candra Lim', serviceBay: null,
      source: 'online',
      createdAt: isoOffset(-1, 19, 0),
      updatedAt: isoOffset(0, 10, 0),
    },

    // ── 15. MENUNGGU KONFIRMASI — walk-in ─────────────────────
    {
      id: 'BK-DEMO0015',
      customerId: 'cust-015',
      customerName: 'Agus Firmansyah',
      customerPhone: '086677889900',
      vehicleDisplay: 'Mitsubishi Pajero Sport - BA 2233 KLM',
      vehiclePlate: 'BA 2233 KLM',
      vehicleId: null,
      serviceId: 'L08',
      serviceName: 'Service Kelistrikan',
      estimatedPrice: 500000,
      estimatedDuration: '2–8 Jam',
      date: in2days,
      time: '08:30',
      notes: 'Power window penumpang depan tidak mau naik.',
      status: S.WAITING_CONFIRMATION,
      voucherCode: null,
      discountApplied: 0,
      confirmedAt: null, confirmedBy: null,
      rejectedAt: null, rejectedReason: null,
      rescheduledAt: null, rescheduledFrom: null, rescheduledTime: null,
      noShowAt: null,
      checkInAt: null, checkInBy: null, orderId: null,
      calendarEntryId: null, mechanicId: null, mechanicName: null, serviceBay: null,
      source: 'walk-in',
      createdAt: isoOffset(0, 11, 15),
      updatedAt: isoOffset(0, 11, 15),
    },
  ]

  sessionStorage.setItem(KEY, JSON.stringify(bookings))
  console.log(`[Seed] ✓ ${bookings.length} booking berhasil di-seed ke garage_bookings`)
  console.log('[Seed] Breakdown status:')
  const counts = bookings.reduce((acc, b) => {
    acc[b.status] = (acc[b.status] || 0) + 1
    return acc
  }, {})
  console.table(counts)
})()
